### ISSUE TITLE
Rake tasks always skipped

### ISSUE THREAD

**Issue by maxdbn** [gkop/elastic-beanstalk-ruby#14]
>   + su -s /bin/bash -c 'bundle exec /opt/elasticbeanstalk/support/scripts/check-for-bundle exec rake-task.rb assets:precompile' webapp
>   bundler: command not found: /opt/elasticbeanstalk/support/scripts/check-for-bundle
>   Install missing gem executables with `bundle install`
>   + echo 'No assets:precompile task in Rakefile, skipping asset compilation.'
>   No assets:precompile task in Rakefile, skipping asset compilation.

>   + su -s /bin/bash -c 'bundle exec /opt/elasticbeanstalk/support/scripts/check-for-bundle exec rake-task.rb db:migrate' webapp
>   bundler: command not found: /opt/elasticbeanstalk/support/scripts/check-for-bundle
>   Install missing gem executables with `bundle install`
>   + echo 'No db:migrate task in Rakefile, skipping database migration.'
>   No db:migrate task in Rakefile, skipping database migration.

I solved it by adding this config:

```
container_commands:
  02_compile-assets:
    command: bundle exec rake assets:precompile
  03_migration:
    command: bundle exec rake db:migrate
```

But is there a way to fix this in your config?

**Comment by gkop** [comment]
Thanks for reporting this, Max!

Truthfully, I have no idea. I no longer use Elastic Beanstalk (moved to Kubernetes).

You're using the Passenger AMI, right?

**Comment by maxdbn** [comment]
@gkop Thank you for answering.
No, I'm using Puma.

I think the problem here is with Elasticbeanstalk itself. If I'm not mistaken, the scripts being executed on these two commands are written by them. I guess it's just poorly maintained.

That's not related but you should change everywhere where you use 

> /opt/elasticbeanstalk/containerfiles/.post-provisioning-complete

to 

> /opt/elasticbeanstalk/support/.post-provisioning-complete

because of that, the first two commands always run instead of just on the first deploy

OTR, Can I ask the reason you moved to Kubernetes?

**Edit:** Saw this other issue: https://github.com/gkop/elastic-beanstalk-ruby/issues/4
He mentions that add_bundle_exec command can be removed because it's done by default. Not sure about that because I needed to execute them by myself after deploying...

**Edit 2:** I've made a gist with the changes I've talked about. You're welcome to update the repository if you like https://gist.github.com/MaxDBN/96a0b281b9df399c932f5f016d5bbfe1

**Comment by gkop** [comment]
Ah, I'm not sure this repo ever worked very well with Puma. I recall the Puma AMI being quite different than the Passenger one.

I moved to Kubernetes because it's not proprietary to Amazon. I never really like Elastic Beanstalk, it felt too hacky.

**Comment by leanguardia** [comment]
In my case I forgot to include the `Rakefile` in the zip of the source code. 


Before including `Rakefile`
```
2023/11/15 15:28:38.062190 [INFO] Running command /bin/su webapp -c bundle exec /opt/elasticbeanstalk/config/private/checkforraketask.rb db:migrate
2023/11/15 15:28:38.415446 [INFO] rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/opt/elasticbeanstalk/config/private/checkforraketask.rb:21:in `<top (required)>'
/bin/bundle:25:in `load'
/bin/bundle:25:in `<main>'
(See full trace by running task with --trace)

023/11/15 15:28:38.415465 [INFO] No db:migrate task in Rakefile, skipping db:migrate.
```

After including it:
```
2023/11/15 15:41:10.369753 [INFO] Running command /bin/su webapp -c bundle exec /opt/elasticbeanstalk/config/private/checkforraketask.rb db:migrate
2023/11/15 15:41:11.109087 [INFO] Found db:migrate task in Rakefile
2023/11/15 15:41:11.109132 [INFO] Running command /bin/su webapp -c bundle exec rake db:migrate
2023/11/15 15:41:12.932420 [INFO] == 20230921024950 CreatePosts: migrating ======================================
-- create_table(:posts)
   -> 0.0099s
== 20230921024950 CreatePosts: migrated (0.0100s) =============================
...
```
