### ISSUE TITLE
yum wkhtmltopdf causes deployment error.

### ISSUE THREAD

**Issue by porteaux** [gkop/elastic-beanstalk-ruby#2]
first thanks for sharing this useful document to the global comunity. I have already installed git, gnuplot, and gsl packages. this is what my current config.ruby looks like:

---

 # These are things that make sense for any Ruby application

 # Install git in order to be able to bundle gems from git
packages

  yum:
    git: []
    gnuplot: []
    gsl: []
 #    wkhtmltopdf: []

commands:
  # Run rake with bundle exec to be sure you get the right version
  add_bundle_exec:
    test: test ! -f /opt/elasticbeanstalk/support/.post-provisioning-complete
    cwd: /opt/elasticbeanstalk/hooks/appdeploy/pre
    command: perl -pi -e 's/(rake)/bundle exec $1/' 11_asset_compilation.sh
  # Bundle with --deployment as recommended by bundler docs
  #   cf. http://gembundler.com/v1.2/rationale.html under Deploying Your Application
  add_deployment_flag:
    test: test ! -f /opt/elasticbeanstalk/support/.post-provisioning-complete
    cwd: /opt/elasticbeanstalk/hooks/appdeploy/pre
    command: perl -pi -e 's/(bundle install)/$1 --deployment/' 10_bundle_install.sh
  # Vendor gems to a persistent directory for speedy subsequent bundling
  make_vendor_bundle_dir:
    test: test ! -f /opt/elasticbeanstalk/support/.post-provisioning-complete
    command: mkdir /var/app/support/vendor_bundle
  # Store the location of vendored gems in a handy env var
  set_vendor_bundle_var:
    test: test ! -f /opt/elasticbeanstalk/support/.post-provisioning-complete
    cwd: /opt/elasticbeanstalk/support
    command: sed -i '12iexport EB_CONFIG_APP_VENDOR_BUNDLE=$EB_CONFIG_APP_SUPPORT/vendor_bundle' envvars
  # The --deployment flag tells bundler to install gems to vendor/bundle/, so
  # symlink that to the persistent directory
  symlink_vendor_bundle:
    test: test ! -f /opt/elasticbeanstalk/support/.post-provisioning-complete
    cwd: /opt/elasticbeanstalk/hooks/appdeploy/pre
    command: sed -i '6iln -s $EB_CONFIG_APP_VENDOR_BUNDLE ./vendor/bundle' 10_bundle_install.sh
  # Don't run the above commands again on this instance
  #   cf. http://stackoverflow.com/a/16846429/283398
  z_write_post_provisioning_complete_file:
    cwd: /opt/elasticbeanstalk/support
    command: touch .post-provisioning-complete

---

when I uncomment:

 #    wkhtmltopdf: []

And then deploy the new version to my eb app.

My eb console for the environment shows:

2013-07-18 09:55:36 UTC-0400    ERROR   Failed to deploy application.
2013-07-18 09:55:35 UTC-0400    ERROR   Responses from [i-59892133] were received, but the commands failed.
2013-07-18 09:55:22 UTC-0400    INFO    Deploying new version to instance(s).

**Comment by nedyalkov** [comment]
@porteaux thank you very much for sharing your solution! It installed everything correctly, but I received "Cannot create a QPixmap when no GUI is being used" error. It seems that version 0.11.0_rc1 requires X to render opacity property.
That's why I tried the version pointed here - http://thelazylog.com/how-to-resolve-cannot-create-a-qpixmap-when-no-gui-is-being-used-when-running-wkhtmltopdf/ - 0.10.0_rc2
It works just fine on server without X :smile:

**Comment by RafalStrab** [comment]
For the latest (0.12.3) version I got this working with below code:
`# install WKHTML
  03_command:
    command: yum install xz urw-fonts libXext openssl-devel libXrender
  04_command:
    command: wget http://download.gna.org/wkhtmltopdf/0.12/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
  05_command:
    command: tar -xJf wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
  06_command:
    command: cp wkhtmltox/bin/wkhtmltopdf /usr/local/bin/wkhtmltopdf
  07_command:
    command: cp wkhtmltox/bin/wkhtmltoimage /usr/local/bin/wkhtmltoimage`

**Comment by RafalStrab** [comment]
For the latest (0.12.3) version I got this working with below code:

03_command: 
  command: yum install xz urw-fonts libXext openssl-devel libXrender
04_command:
  command: wget http://download.gna.org/wkhtmltopdf/0.12/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
05_command:
  command: tar -xJf wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
06_command:
  command: cp wkhtmltox/bin/wkhtmltopdf /usr/local/bin/wkhtmltopdf
07_command:
  command: cp wkhtmltox/bin/wkhtmltoimage /usr/local/bin/wkhtmltoimage

Forgive me not having proper YAML format but I wasn't able to format it.
